[build]
target = "xtensa-esp32s3-espidf"
target-dir = "/tmp/rustTmp/target"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --baud=921600 --monitor --flash-size 16mb"
rustflags = ["--cfg", "espidf_time64", "--cfg", "esp_idf_comp_vfs_enabled"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32s3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.4.1"

# 设置了target-dir, 则必须设置这个变量
CARGO_WORKSPACE_DIR = { value = "", relative = true }
# 指定esp-idf路径
IDF_PATH="/home/esp/esp-idf"
# 指定esp-idf工具安装路径
ESP_IDF_TOOLS_INSTALL_DIR = "custom:/home/esp/.embuild"

